### ISSUE TITLE
事件分发有问题

### ISSUE THREAD

**Issue by mamumu** [workertao/AcodeHrLayout#1]

**Comment by workertao** [comment]
可否详细说一下，那块有问题？

**Comment by mamumu** [comment]
当向上滑动后，如果内部列表需要滑动（列表没有滑动到顶部或者底部，则判定列表需要消费滑动），则列表消费滑动，如果内部没有消费，则外部的你定义的这个布局消费滑动。我试了下demo，滑动有冲突，而且我在recyclerview平级加了个view，发现滑不动，期望解决

**Comment by workertao** [comment]
已尝试修改，但不确定是不是你这种情况。如果还不行，+Q1240490684联系我，获取把xml贴出来。

**Comment by mamumu** [comment]
无法加好友，Android和ios哪个吊？母鸡

**Comment by workertao** [comment]
不好意思，再试一次。
